(custom-set-variables
 ;; custom-set-variables was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 '(\.nil nil t)
 '(anzu-deactivate-region t)
 '(anzu-mode-lighter "")
 '(anzu-replace-threshold 50)
 '(anzu-replace-to-string-separator " => ")
 '(anzu-search-threshold 1000)
 '(auth-sources '((:source "~/.authinfo.gpg" :host t :protocol t)))
 '(backup-directory-alist '(("." . "~/.emacs.d/backups")))
 '(cider-auto-select-error-buffer t t)
 '(cider-repl-history-size 1000 t)
 '(cider-repl-pop-to-buffer-on-connect nil t)
 '(cider-repl-use-clojure-font-lock t t)
 '(cider-repl-wrap-history t t)
 '(cider-show-error-buffer t t)
 '(company-box-backends-colors nil t)
 '(company-box-doc-delay 0.3)
 '(company-box-enable-icon t)
 '(company-dabbrev-downcase nil)
 '(company-dabbrev-ignore-case nil)
 '(company-idle-delay 0)
 '(company-minimum-prefix-length 1)
 '(company-quickhelp-delay 0.3)
 '(company-tooltip-align-annotations t)
 '(company-tooltip-limit 20)
 '(custom-enabled-themes '(sanityinc-tomorrow-night))
 '(custom-file "~/.emacs.d/emacs-custom.el")
 '(custom-safe-themes
   '("06f0b439b62164c6f8f84fdda32b62fb50b6d00e8b01c2208e55543a6337433a" default))
 '(dired-recursive-copies 'always)
 '(dired-recursive-deletes 'always)
 '(enable-recursive-minibuffers t)
 '(eshell-highlight-prompt nil t)
 '(eshell-prompt-function 'epe-theme-lambda t)
 '(flycheck-check-syntax-automatically '(save mode-enabled))
 '(flycheck-emacs-lisp-initialize-packages t)
 '(flycheck-emacs-lisp-load-path 'inherit)
 '(flycheck-posframe-inhibit-functions '((lambda (&rest _) (bound-and-true-p company-backend))))
 '(inhibit-startup-screen t)
 '(ivy-display-style 'fancy)
 '(ivy-initial-inputs-alist nil)
 '(ivy-re-builders-alist '((t . ivy--regex-fuzzy)) t)
 '(ivy-use-virtual-buffers t)
 '(kill-whole-line t)
 '(lexical-binding t t)
 '(mouse-yank-at-point t)
 '(nrepl-hide-special-buffers t t)
 '(nrepl-popup-stacktraces nil t)
 '(package-archives
   '(("gnu" . "https://mirrors.bfsu.edu.cn/elpa/gnu/")
     ("melpa" . "https://mirrors.bfsu.edu.cn/elpa/melpa/")))
 '(package-selected-packages
   '(markdown-mode synosaurus flyspell-popup flyspell-correct-popup flyspell-correct-ivy flyspell-correct gcmh auto-fill-mode company-auctex company-math tex delete-selection flycheck-inline anzu mwim multiple-cursors flx paredit diredfl eshell-syntax-highlighting eshell-prompt-extras yaml-mode expand-region iedit wgrep undo-fu-session undo-fu beginend aggressive-indent clojure-mode-extra-font-locking cider clojure-mode company-statistics company-quickhelp company-box company yasnippet-snippets yasnippet flycheck-clj-kondo flycheck-posframe flycheck gitignore-mode diff-hl magit hungry-delete which-key rainbow-delimiters mood-line color-theme-sanityinc-tomorrow counsel ivy leaf-keywords leaf))
 '(recentf-auto-cleanup 'never)
 '(recentf-max-menu-items 15)
 '(recentf-max-saved-items 500)
 '(save-abbrevs 'silently)
 '(savehist-additional-variables '(kill-ring search-ring compile-command regexp-search-ring))
 '(uniquify-after-kill-buffer-p t)
 '(uniquify-buffer-name-style 'style nil (uniquify))
 '(uniquify-ignore-buffers-re "^\\*")
 '(uniquify-separator "/")
 '(url-proxy-services
   '(("no_proxy" . "^\\(localhost\\|10\\..*\\|192\\.168\\..*\\)")
     ("http" . "localhost:8888")
     ("https" . "localhost:8888")))
 '(user-full-name "Alex Yan")
 '(user-mail-address "yanda1987@outlook.com")
 '(vc-follow-link t t)
 '(visual-bell t t)
 '(whitespace-line-column 80)
 '(whitespace-style '(face tabs empty trailing lines-tail)))
(custom-set-faces
 ;; custom-set-faces was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 )
